"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import Header from "./Comp/Header";
import { useEffect } from "react";
import Footer from "./Comp/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.min.js");
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}
        <Footer/>
      </body>
    </html>
  );
}
